[versions]
# Kotlin
kotlin = '1.8.20'
kotlin-wrappers-js = '1.0.0-pre.593'
# AGP
android-build-tools = '8.0.2'
# Compose
compose = '1.4.0'
compose-compiler = '1.4.6'
compose-multiplatform = '1.4.0'
compose-detekt-rules = '0.0.26'
compose-runtime-tracing = '1.0.0-alpha03'
# AndroidX
core-ktx = '1.10.1'
appcompat = '1.6.1'
lifecycle-runtime-ktx = '2.6.1'
activity-compose = '1.7.2'
androidx-profile-installer = '1.3.1'
# Google
material = '1.9.0'
# KotlinX
kotlinx-serialization-json = '1.5.1'
kotlinx-collections-immutable = '0.3.5'
kover = '0.5.1'
# Test
junit = '4.13.2'
androidx-test-junit-ext = '1.1.5'
androidx-test-espresso-core = '3.5.1'
macrobenchmark = '1.2.0-alpha16'
ui-automator = '2.2.0'
androidx-test-rules = '1.5.0'
# Other
detekt = '1.23.0'
gradle-nexus-plugin = '1.1.0'
dokka = '1.8.20'

[libraries]
# Kotlin
kotlin-wrappers-js = { group = "org.jetbrains.kotlin-wrappers", name = "kotlin-js", version.ref = "kotlin-wrappers-js" }
# Compose
compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose" }
compose-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "compose" }
compose-material = { group = "androidx.compose.material", name = "material", version.ref = "compose" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose" }
compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "compose" }
compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "compose" }
compose-runtime-tracing = { group = "androidx.compose.runtime", name = "runtime-tracing", version.ref = "compose-runtime-tracing" }
compose-detekt-rules = { group = "com.twitter.compose.rules", name = "detekt", version.ref = "compose-detekt-rules" }
# AndroidX
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
androidx-profile-installer = { group = "androidx.profileinstaller", name = "profileinstaller", version.ref = "androidx-profile-installer" }
# Google
google-material = { group = "com.google.android.material", name = "material", version.ref = "material" }
# KotlinX
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
kotlinx-collections-immutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "kotlinx-collections-immutable" }
# Test
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-junit-ext" }
androidx-test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidx-test-espresso-core" }
macrobenchmark-junit = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "macrobenchmark" }
ui-automator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "ui-automator" }
androidx-test-rules = { group = "androidx.test", name = "rules", version.ref = "androidx-test-rules" }

[plugins]
# Android
android-app = { id = "com.android.application", version.ref = "android-build-tools" }
android-lib = { id = "com.android.library", version.ref = "android-build-tools" }
android-test = { id = "com.android.test", version.ref = "android-build-tools" }
# Kotlin
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
# Compose
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
# KotlinX
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlinx-kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
# Other
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
nexus-publish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "gradle-nexus-plugin" }
